---
title: "Create descriptive tables"
author: "Kate Tran"
date: "7/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tableone)
library(sjPlot)
library(tidyr)
library(janitor)
library(purrr)
library(nortest)
source("../utility_fun.R")
```

```{r}
data_wide <- read.csv("../data/dataset_wide.csv")
data_long <- read.csv("../data/dataset_long.csv")
```

```{r}
# Numbers in abstract
## Total N
N <- length(unique(data_wide$src_subject_id)) # 11873
## Mean age at baseline
data_long %>% filter(eventname == "baseline_year_1_arm_1") %>% summarise(mean = mean(interview_age, na.rm = T)/12) # 9.915087
data_long %>% filter(eventname == "baseline_year_1_arm_1") %>% summarise(sd = sd(interview_age, na.rm = T)/12) # 0.6246999
## % of females
prop.table(table(data_wide$sex_br))
## % of headache
table(data_wide$headache_ever) # 907
907/N

prop.table(table(data_long$medhx_2q_l[data_long$eventname == "baseline_year_1_arm_1"]))
prop.table(table(data_long$medhx_2q_l[data_long$eventname == "1_year_follow_up_y_arm_1"]))
prop.table(table(data_long$medhx_2q_l[data_long$eventname == "2_year_follow_up_y_arm_1"]))

## Discovery sample
abcd_gr1 <- read_rds("../outputs/abcd_gr1.rds")
abcd_gr1_wide <-
    abcd_gr1 %>% select(matches("src|eventname|medhx_2q_l")) %>% 
    pivot_wider(., names_from = eventname, values_from = medhx_2q_l) %>%
    remove_empty(., which = c("rows", "cols"), quiet = TRUE)

abcd_gr1_wide <- create_ever_var(data = abcd_gr1_wide, search_term = "year", new_col_name = "headache_ever")

## discovery subsample (n=XX, YY headache) (5784, 426 (13.39%))
length(unique(abcd_gr1$src_subject_id))
table(abcd_gr1_wide$headache_ever)
prop.table(table(abcd_gr1_wide$headache_ever))

## Testing sample
abcd_gr2 <- read_rds("../outputs/abcd_gr2.rds")
abcd_gr2_wide <-
    abcd_gr2 %>% select(matches("src|eventname|medhx_2q_l|migraine_PRS_EUR")) %>% 
    pivot_wider(., names_from = eventname, values_from = medhx_2q_l) %>%
    remove_empty(., which = c("rows", "cols"), quiet = TRUE)

abcd_gr2_wide <- create_ever_var(data = abcd_gr2_wide, search_term = "year", new_col_name = "headache_ever")
## testing subsample (n=XX, YY headache) (5784, 459 (14.69%))
length(unique(abcd_gr2$src_subject_id))
table(abcd_gr2_wide$headache_ever)
prop.table(table(abcd_gr2_wide$headache_ever))

# Number of subjects EUR
length(unique(abcd_gr2$src_subject_id[!is.na(abcd_gr2$migraine_PRS_EUR)])) #2831
# table(!is.na(abcd_gr2_wide$migraine_PRS_EUR)) #2831

## % headache among EUR
abcd_gr2_wide %>% filter(!is.na(migraine_PRS_EUR)) %>% select(headache_ever) %>% table() #226 (226/2831 = 7.98%)
table(abcd_gr2_wide$headache_ever[!is.na(abcd_gr2_wide$migraine_PRS_EUR)])

# Table shows the number of headache at each timepoint
CreateTableOne(
            data = data_long,
            vars = "medhx_2q_l",
            strata = "eventname",
            factorVars = "medhx_2q_l",
            includeNA = T)


# Number of variables (continuous, binary, Likert) among 98
vars <- readRDS("../outputs/vars_98.rds")
# binary 70
data_long %>%  select(all_of(vars)) %>%  map_df(~range(., na.rm = T)) %>% select_if(~ max(., na.rm = T) - min(., na.rm = T) == 1) %>% names() %>% length()
# data_long %>%  select(all_of(vars)) %>%  map_df(~range(., na.rm = T)) %>% View()
```

```{r}
# table 1: by headache ever
table1_var <- data_wide %>% 
    select(matches(c("age_years$", "sex_br", "race", "ethnicity", "_income$"))) %>% #"poverty_line$", 
    names()

table1_factor <- table1_var[!table1_var %in% c("age_years", "household_income")]

# Check normality of continuous variables

ad.test(data_wide$age_years) # not normal
ad.test(data_wide$household_income) # not normal

# Check if need to use Fisher's exact test
check_test_type(data = data_wide, var_list = table1_factor, reference_var = "headache_ever") # All Chi-square test


write.csv(
    print(
        CreateTableOne(
            data = data_wide,
            vars = table1_var,
            strata = "headache_ever",
            factorVars = table1_factor,
            includeNA = T,
            addOverall = T
        ),
        pDigits = 5,
        catDigits = 2,
        contDigits = 2,
        nonnormal = c("age_years", "household_income")
    ),
    "../outputs/table1_main_values_072423.csv"
)

chisq.test(data_wide$ethnicity_hisp , data_wide$headache_ever, correct = TRUE )$p.value

# FDR-adjusted p-values
# table1_adj_p <-  round(p.adjust(c(0.01804, 0.74665, 1, 0.00161, 0.00013, 0.94645, 0.58277, 0.95751, 0.00021, 0.94727, 0.00001), method = "fdr"), 3)
table1_adj_p <-  round(p.adjust(c(0.01552, 0.74665, 1, 0.00161, 0.00013, 0.94645, 0.58277, 0.95751, 0.00021, 0.94727, 0.00001), method = "fdr"), 3)


# household income bins in each group
write.csv(
    print(
        CreateTableOne(
            data = data_wide,
            vars = "household_income",
            strata = "headache_ever",
            factorVars = "household_income",
            includeNA = T
        )
    ),
    "../outputs/table1_income_bins.csv"
)
```

```{r}
# Table 2: internal validation headache and medication/PRS
mod_headache_med1 <- glmer(data = data_long, 
                           medhx_2q_l ~ Daily.Preventive.medications_2w + scale(age_years) + scale(age_years)^2 + scale(age_years)^3  + 
                               sex_br + race_black + race_white + household_income + ethnicity_hisp +
                               (1 | site_id_l_br/rel_family_id/src_subject_id), family = binomial, nAGQ = 0)

mod_headache_med2 <- glmer(data = data_long, 
                           medhx_2q_l ~ Rescue.Medications_2w + scale(age_years) + scale(age_years)^2 + scale(age_years)^3  + 
                               sex_br + race_black + race_white + household_income + ethnicity_hisp +
                               (1 | site_id_l_br/rel_family_id/src_subject_id), family = binomial, nAGQ = 0)

mod_headache_prs <- glmer(data = data_long %>% filter(genetic_afr == 0), 
                          medhx_2q_l ~ migraine_PRS_EUR + scale(age_years) + scale(age_years)^2 + scale(age_years)^3  + 
                              sex_br +
                              (1 | site_id_l_br/rel_family_id/src_subject_id), family = binomial, nAGQ = 0)

tab_model(mod_headache_med1, mod_headache_med2, mod_headache_prs, show.intercept = F, digits = 3)


# New approach - will choose later after Ran finalize the paper
chisq.test(table(data_long$Daily.Preventive.medications_2w, data_long$medhx_2q_l))
chisq.test(table(data_long$Rescue.Medications_2w, data_long$medhx_2q_l))
# t.test(data_long$migraine_PRS_EUR, data_long$medhx_2q_l)
```

```{r}
# etable 2: internal validation # by headache
etable3_var <- c("daily_med_2w_ever", "rescue_med_2w_ever") #, "migraine_PRS_EUR"

check_test_type(data = data_wide, var_list = etable3_var, reference_var = "headache_ever") # All Chi-square test

write.csv(
    print(
        CreateTableOne(
            data = data_wide,
            vars = etable3_var,
            strata = "headache_ever",
            factorVars = etable3_var,
            includeNA = T,
            addOverall = T
        ),
        missing = T,
        pDigits = 5,
        catDigits = 2,
        contDigits = 2
    ),
    "../outputs/etable2_main_values_072423.csv"
)

table2_adj_p <- round(p.adjust(c(0.00001, 0.00001), method = "fdr"), 3)

# Get number of missing data
naniar::miss_var_summary(data_wide %>% filter(!is.na(headache_ever)) %>% select(all_of(table1_var)))
```


