---
title: "Main analysis"
author: "Kate Tran"
date: "7/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Library
```{r}
library(sjPlot) 
library(stringr)
library(performance)
library(janitor)
library(dplyr)
library(purrr)
library(qgraph)
library(caret)
source("../utility_fun.R")
source("../config.R")
```

# Read data
```{r}
data_long <- read.csv("../data/dataset_long.csv")
```

# Create discovery and testing subsets
```{r}
# ABCD dataset 1 & 2
abcd_gr1 <- readRDS("../outputs/abcd_gr1.rds")
abcd_gr2 <- readRDS("../outputs/abcd_gr2.rds")
vars <- readRDS("../outputs/vars_98.rds")
```

# Univariate models on abcd_gr1
```{r}
# Run univariate models on the first half of the data: abcd_gr1
# vars <- data_long %>% 
#     dplyr::select(matches(c("d_inc|famhx_ss_mom|dim_y|harm(2?)$|bully|hood(_?)[^_P]|nsc_|adi.*_[irmp]|pmq|fes_y.*_fc$|crpbi|srpf|macv_y.*fs|ple.*[^fu]_(y|fu_y_bad)$|hx.*[26][ij]|tbi.*_l$|tbi_[123457]|cat$|alcohol$|tobacco$"))) %>% names() # 98 vars
# 
# saveRDS(vars, "../outputs/vars_98.rds")
```

# Run univariate models
```{r}
# Exwas 1 on original variables - get significant variables - Not FDR corrected p-values for headache project - No covariates
exwas_headache <- exwas(data_train = abcd_gr1, vars = vars, outcome = "medhx_2q_l", data_test = abcd_gr2)
univariate_headache <- exwas_headache$univariate_models_dat

# eTable3
univariate_headache_sig <- exwas_headache$univariate_models_sig %>% 
    mutate(low_ci = round(exp(low_ci), 2), high_ci = round(exp(high_ci), 2), 
           CI_90 = paste0(low_ci, " - ", high_ci), p_value = round(p_value, 3)) %>% 
    select(variable, OR, CI_90, p_value) %>% 
    arrange(OR)

write.csv(univariate_headache_sig, "../outputs/univariate_headache_sig_070523.csv")

sig_vars <- univariate_headache_sig %>% pull(variable)

saveRDS(univariate_headache, file = "../outputs/univariate_plot_abcdgr1_coef_070523.rds")
```

# Check correlation of significant variables
```{r}
png("../plots/correlation_sig_21vars.png", units="in", width = 10, height = 10, res = 620)
cor_vars <- data_long %>% select(all_of(sig_vars))
corrs = cor_auto(cor_vars)

# May remove this one afterall, depending on how Ran responses to Sinan's comment
testRes = cor.mtest(cor_vars, conf.level = 0.95)

corrplot(corrs, p.mat = testRes$p, method = 'color', diag = FALSE, type = 'upper',
         sig.level = c(0.001, 0.01, 0.05), pch.cex = 0.7,
         insig = 'label_sig', pch.col = 'grey20', order = 'original', tl.col = "black", tl.srt = 45, tl.cex = 0.7, cl.cex = 0.8, cl.ratio = 0.2)
```

# Generate exposome score
```{r}
# Get weight from abcd_gr1 # but use binary variables of Likert variables only
# Exwas 2 on updated variables (with binary variables) - get coefficients
sig_vars_bin <- sig_vars
# Dichotomize 2 Likert variables
sig_vars_bin[sig_vars_bin == "tbi_ss_worst_overall_l"] <- "tbi_worst_overall"
sig_vars_bin[sig_vars_bin == "neighborhood3r_p"] <- "neighborh_notsafe"

exwas_headache_binary <- exwas(data_train = abcd_gr1, vars = sig_vars_bin, outcome = "medhx_2q_l", data_test = abcd_gr2)
abcd_gr2_weight <- exwas_headache_binary$data_test_exposome
```

# Multivariate models in the main result
```{r}
# Table 3
mod1 <- glmer(medhx_2q_l ~ (1 | site_id_l_br/rel_family_id/src_subject_id) + 
                   age_years + age_years^2 + age_years^3 + sex_br + race_black + ethnicity_hisp,
              nAGQ = 0, family = binomial, data = abcd_gr2_weight %>% filter(genetic_afr == 0))

mod2 <- glmer(medhx_2q_l ~ scale(weighted_exposome) + (1 | site_id_l_br/rel_family_id/src_subject_id) + 
                   age_years + age_years^2 + age_years^3 + sex_br + race_black + ethnicity_hisp, 
              nAGQ = 0, family = binomial, data = abcd_gr2_weight %>% filter(genetic_afr == 0))

mod3 <- glmer(medhx_2q_l ~ migraine_PRS_EUR + (1 | site_id_l_br/rel_family_id/src_subject_id) + 
                   age_years + age_years^2 + age_years^3 + sex_br + race_black + ethnicity_hisp, 
              nAGQ = 0, family = binomial, data = abcd_gr2_weight %>% filter(genetic_afr == 0))

mod4 <- glmer(medhx_2q_l ~ scale(weighted_exposome) + migraine_PRS_EUR + (1 | site_id_l_br/rel_family_id/src_subject_id) + 
                   age_years + age_years^2 + age_years^3 + sex_br + race_black + ethnicity_hisp, 
              nAGQ = 0, family = binomial, data = abcd_gr2_weight %>% filter(genetic_afr == 0))

mod5 <- glmer(medhx_2q_l ~ scale(weighted_exposome) * migraine_PRS_EUR + (1 | site_id_l_br/rel_family_id/src_subject_id) + 
                   age_years + age_years^2 + age_years^3 + sex_br + race_black + ethnicity_hisp, 
              nAGQ = 0, family = binomial, data = abcd_gr2_weight %>% filter(genetic_afr == 0))

com1 <- tab_model(mod1, mod2, mod3, mod4, mod5)

# R2
r2(mod1)[2]
r2(mod2)[2]
r2(mod3)[2]
r2(mod4)[2]
r2(mod5)[2]

anova(mod1, mod2, test="Chisq")
anova(mod1, mod3, test="Chisq")
anova(mod2, mod3, test="Chisq")
anova(mod2, mod4, test="Chisq")
anova(mod3, mod4, test="Chisq") 
anova(mod4, mod5, test="Chisq") 

# adj p
round(p.adjust(c(9.83e-12, 0.0007253, 0, 0.001058, 1.406e-11, 0.07701), method = "fdr"), 3)
```

# Supplement - models on whole cohort
```{r}
# eTable 4
mod21 <- glmer(medhx_2q_l ~ (1 | site_id_l_br/rel_family_id/src_subject_id) + 
                 age_years + age_years^2 + age_years^3 + 
                   sex_br + race_black + race_white + ethnicity_hisp,
              nAGQ = 0, family = binomial, data = abcd_gr2_weight) # all population

mod22 <- glmer(medhx_2q_l ~ weighted_exposome + (1 | site_id_l_br/rel_family_id/src_subject_id) + 
                 age_years + age_years^2 + age_years^3 + 
                   sex_br + race_black + race_white + ethnicity_hisp, 
              nAGQ = 0, family = binomial, data = abcd_gr2_weight) # all population

com2 <- tab_model(mod21, mod22)

r2(mod21)[2]
r2(mod22)[2]

anova(mod21, mod22, test="Chisq")
```

# Sensitivity analysis # Removed correlated among 21 significant variables at cutoff 0.9
```{r}
# Remove correlated variables among 21 significant variables at 0.9 cut-off
cor_vars <- abcd_gr1 %>% select(all_of(sig_vars))
corrs = cor_auto(cor_vars)
corr_vars_rm <- findCorrelation(corrs, cutoff = 0.9, exact = T, names = T, verbose = T) #medhx_6i_l
abcd_gr1_0.9 <- abcd_gr1 %>% select(-all_of(corr_vars_rm)) # remove correlated variables from training dataset abcd_gr1
# Don't need to re-run exwas among new set of variables as all of those were run with the same outcome
# Only medhx_6i_l was removed, thus, we can use sig_vars_bin excluding medhx_6i_l for exposome score (after Dichotomize 2 Likert variables)
sig_vars_bin_0.9 <- sig_vars_bin[!sig_vars_bin %in% corr_vars_rm]

exwas_headache_binary_0.9 <- exwas(data_train = abcd_gr1_0.9, vars = sig_vars_bin_0.9, outcome = "medhx_2q_l", data_test = abcd_gr2)
abcd_gr2_weight_0.9 <- exwas_headache_binary_0.9$data_test_exposome
# Re-run models
mod1_0.9 <- glmer(medhx_2q_l ~ (1 | site_id_l_br/rel_family_id/src_subject_id) + 
                   age_years + age_years^2 + age_years^3 + sex_br + race_black + ethnicity_hisp,
              nAGQ = 0, family = binomial, data = abcd_gr2_weight_0.9 %>% filter(genetic_afr == 0))

mod2_0.9 <- glmer(medhx_2q_l ~ scale(weighted_exposome) + (1 | site_id_l_br/rel_family_id/src_subject_id) + 
                   age_years + age_years^2 + age_years^3 + sex_br + race_black + ethnicity_hisp, 
              nAGQ = 0, family = binomial, data = abcd_gr2_weight_0.9 %>% filter(genetic_afr == 0))

mod3_0.9 <- glmer(medhx_2q_l ~ migraine_PRS_EUR + (1 | site_id_l_br/rel_family_id/src_subject_id) + 
                   age_years + age_years^2 + age_years^3 + sex_br + race_black + ethnicity_hisp, 
              nAGQ = 0, family = binomial, data = abcd_gr2_weight_0.9 %>% filter(genetic_afr == 0))

mod4_0.9 <- glmer(medhx_2q_l ~ scale(weighted_exposome) + migraine_PRS_EUR + (1 | site_id_l_br/rel_family_id/src_subject_id) + 
                   age_years + age_years^2 + age_years^3 + sex_br + race_black + ethnicity_hisp, 
              nAGQ = 0, family = binomial, data = abcd_gr2_weight_0.9 %>% filter(genetic_afr == 0))

mod5_0.9 <- glmer(medhx_2q_l ~ scale(weighted_exposome) * migraine_PRS_EUR + (1 | site_id_l_br/rel_family_id/src_subject_id) + 
                   age_years + age_years^2 + age_years^3 + sex_br + race_black + ethnicity_hisp, 
              nAGQ = 0, family = binomial, data = abcd_gr2_weight_0.9 %>% filter(genetic_afr == 0))

com1_0.9 <- tab_model(mod1_0.9, mod2_0.9, mod3_0.9, mod4_0.9, mod5_0.9)

# R2
r2(mod1_0.9)[2]
r2(mod2_0.9)[2]
r2(mod3_0.9)[2]
r2(mod4_0.9)[2]
r2(mod5_0.9)[2]

anova(mod1_0.9, mod2_0.9, test="Chisq")
anova(mod1_0.9, mod3_0.9, test="Chisq")
anova(mod2_0.9, mod3_0.9, test="Chisq")
anova(mod2_0.9, mod4_0.9, test="Chisq")
anova(mod3_0.9, mod4_0.9, test="Chisq") 
anova(mod4_0.9, mod5_0.9, test="Chisq") 

# adj p
round(p.adjust(c(4.361e-11, 0.0007253, 0, 0.001132, 6.65e-11, 0.0846), method = "fdr"), 3)
```






